=== kosoup/Customs-Automation/references/전자상거래 수출관련 서식/GOVCBRDJQ/KCS_DeclarationOfEXP_DJQSchemaModule_1.0_standard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Module: KCS_DeclarationOfEXP_DJQ
Name: 전자상거래 수출신고 정정취하 신청서
Agency: Korea Customs Service
KCSBusinessType : EXP
AgencyAssignedCustomizedDocumentName : GOVCBR_DJQ
Version: 1.0 Rev. 0
Last change: 2019.11.08
Author : yh.kim

Change :
 
 Copyright (C) Korea Customs Service (2014). All Rights Reserved. 
-->
<xsd:schema xmlns="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJQSchemaModule:1:0" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:ds="urn:wco:datamodel:WCO:DS:1" xmlns:kcsds="urn:kr:gov:kcs:data:standard:KCSDS:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJQSchemaModule:1:0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:import namespace="urn:wco:datamodel:WCO:DS:1" schemaLocation="../../../wco/common/DS_1p0.xsd"/>
	<xsd:import namespace="urn:kr:gov:kcs:data:standard:KCSDS:1" schemaLocation="../../common/KCSDS_1p0.xsd"/>
	<xsd:element name="Declaration">
		<xsd:complexType>
			<xsd:sequence>
				<!--신청세관/과-->
				<xsd:element name="DeclarationOfficeID" type="ds:DeclarationDeclarationOfficeIDType"/>
				<!--구분-->
				<xsd:element name="FunctionCode" type="ds:DeclarationFunctionCodeType"/>
				<!--전자상거래수출신고번호-->
				<xsd:element name="ID" type="ds:DeclarationIdentificationIDType"/>
				<!--신청일자-->
				<xsd:element name="IssueDateTime" type="ds:DeclarationIssueDateTimeType"/>
				<!--문서형태구분-->
				<xsd:element name="TypeCode" type="ds:DeclarationTypeCodeType"/>
				<!--신청차수-->
				<xsd:element name="VersionID" type="ds:DeclarationVersionIDType"/>
				<!--신고구분-->
				<xsd:element name="TransactionNatureCode" type="ds:DeclarationTransactionNatureCodeType"/>
				<!--귀책사유-->
				<xsd:element name="Reason" type="kcsds:DeclarationReasonTextType"/>
				<xsd:element name="AdditionalInformation" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<!--정정/취하/연장사유-->
							<xsd:element name="Content" type="ds:AdditionalInformationContentTextType" minOccurs="0"/>
							<!--정정/취하코드-->
							<xsd:element name="StatementCode" type="ds:AdditionalInformationStatementCodeType" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Amendment" minOccurs="0" maxOccurs="999">
					<xsd:complexType>
						<xsd:sequence>
							<!--구분-->
							<xsd:element name="ChangeReasonCode" type="ds:AmendmentChangeReasonCodeType" minOccurs="0"/>
							<!--정정전-->
							<xsd:element name="StatementDescription" type="ds:AmendmentStatementDescriptionTextType" minOccurs="0"/>
							<!--정정후-->
							<xsd:element name="AdjustmentDescription" type="kcsds:AmendmentAdjustmentDescriptionTextType" minOccurs="0"/>
							<xsd:element name="Pointer">
								<xsd:complexType>
									<xsd:sequence>
										<!--정정항목 란번호-->
										<xsd:element name="SequenceNumeric" type="ds:PointerSequenceNumericType"/>
										<!--규격번호-->
										<xsd:element name="DocumentSectionCode" type="ds:PointerDocumentSectionCodeType"/>
										<!--항목번호-->
										<xsd:element name="TagID" type="ds:PointerTagIDType"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Exporter">
					<xsd:complexType>
						<xsd:sequence>
							<!--수출화주 통관고유부호-->
							<xsd:element name="ID" type="ds:ExporterIdentificationIDType" minOccurs="0"/>
							<!--수출화주상호-->
							<xsd:element name="Name" type="ds:ExporterNameTextType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== kosoup/Customs-Automation/references/전자상거래 수출관련 서식/GOVCBRDJQ/KCS_DeclarationOfEXP_DJQSchemaModule_1.0_standard.xml
<?xml version="1.0" encoding="UTF-8"?>
<wco:Declaration
    xmlns:kcs="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJQSchemaModule:1:0"
    xmlns:wco="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJQSchemaModule:1:0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJQSchemaModule:1:0 ../../schema4G/kcs/data/standard/KCS_DeclarationOfEXP_DJQSchemaModule_1.0_standard.xsd">
    <!--신청세관/과-->
    <wco:DeclarationOfficeID>01001</wco:DeclarationOfficeID>
    <!--구분-->
    <wco:FunctionCode>01</wco:FunctionCode>
    <!--전자상거래수출신고번호-->
    <wco:ID>99999999</wco:ID>
    <!--신청일자-->
    <wco:IssueDateTime>20191108</wco:IssueDateTime>
    <!--문서형태구분-->
    <wco:TypeCode>GOVCBRDJP</wco:TypeCode>
    <!--신청차수-->
    <wco:VersionID>01</wco:VersionID>
    <!--신고구분-->
    <wco:TransactionNatureCode>01</wco:TransactionNatureCode>
    <!--귀책사유-->
    <kcs:Reason>01</kcs:Reason>
    
    <wco:AdditionalInformation>
        <!--정정/취하/연장사유-->
        <wco:Content>연장사유</wco:Content>
        <!--정정/취하코드-->
        <wco:StatementCode>01</wco:StatementCode>
    </wco:AdditionalInformation>
    
	<!-- 1..999 -->
    <wco:Amendment>
        <!--구분-->
        <wco:ChangeReasonCode>01</wco:ChangeReasonCode>
        <!--정정전-->
        <wco:StatementDescription>정정전</wco:StatementDescription>
        <!--정정후-->
        <kcs:AdjustmentDescription>정정후</kcs:AdjustmentDescription>
		<wco:Pointer>
			<!--정정항목 란번호-->
			<wco:SequenceNumeric>1</wco:SequenceNumeric>
			<!--규격번호-->
			<wco:DocumentSectionCode>01</wco:DocumentSectionCode>
			<!--항목번호-->
			<wco:TagID>01</wco:TagID>
		</wco:Pointer>
    </wco:Amendment>
    
    <wco:Exporter>
        <!--수출화주 통관고유부호-->
        <wco:ID>999999999</wco:ID>
        <!--수출화주의 상호 또는 성명-->
        <wco:Name>상호</wco:Name>
    </wco:Exporter>
</wco:Declaration>
