=== kosoup/Customs-Automation/references/수출정정신고/KCS_DeclarationOfEXP_5ASSchemaModule_1.0_standard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Module: KCS_DeclarationOfEXP_5AS
Name: 수출신고 정정·적재기간연장 승인(신청)서
Agency: Korea Customs Service
KCSBusinessType : EXP
AgencyAssignedCustomizedDocumentName : GOVCBR_5AS
Version: 1.0 Rev. 0
Last change: 2023.11.03
Author : opm308

Change : 
	2014.04.14
		- 구분, 규격번호, 정정전, 정정후 조건 변경.
	2023.11.03
		- 서식명변경: 수출신고수리 정정/취하 승인(신청)서 → 수출신고 정정/적재기간연장 승인(신청)서
		- 항목병변경: 정정/취하코드 → 정정코드, 정정/취하/연장사유 → 정정/연장사유

Copyright (C) Korea Customs Service (2014). All Rights Reserved. 
-->
<xsd:schema xmlns="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_5ASSchemaModule:1:0" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:ds="urn:wco:datamodel:WCO:DS:1" xmlns:kcsds="urn:kr:gov:kcs:data:standard:KCSDS:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_5ASSchemaModule:1:0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:import namespace="urn:wco:datamodel:WCO:DS:1" schemaLocation="../../../wco/common/DS_1p0.xsd"/>
	<xsd:import namespace="urn:kr:gov:kcs:data:standard:KCSDS:1" schemaLocation="../../common/KCSDS_1p0.xsd"/>
	<xsd:element name="Declaration">
		<xsd:complexType>
			<xsd:sequence>
				<!--확정일자-->
				<xsd:element name="AcceptanceDateTime" type="ds:DeclarationAcceptanceDateTimeType" minOccurs="0"/>
				<!--신고세관/과-->
				<xsd:element name="DeclarationOfficeID" type="ds:DeclarationDeclarationOfficeIDType"/>
				<!--수출신고번호-->
				<xsd:element name="ID" type="ds:DeclarationIdentificationIDType"/>
				<!--신청일자(CCYYMMDD)-->
				<xsd:element name="IssueDateTime" type="ds:DeclarationIssueDateTimeType"/>
				<!--문서형태구분-->
				<xsd:element name="TypeCode" type="ds:DeclarationTypeCodeType"/>
				<!--신청차수-->
				<xsd:element name="VersionID" type="ds:DeclarationVersionIDType"/>
				<!--구분-->
				<xsd:element name="TransactionNatureCode" type="ds:DeclarationTransactionNatureCodeType"/>
				<!--귀책사유-->
				<xsd:element name="Reason" type="kcsds:DeclarationReasonTextType"/>
				<xsd:element name="AdditionalInformation">
					<xsd:complexType>
						<xsd:sequence>
							<!--정정코드-->
							<xsd:element name="StatementCode" type="ds:AdditionalInformationStatementCodeType"/>
							<!--정정/연장사유-->
							<xsd:element name="StatementDescription" type="ds:AdditionalInformationStatementDescriptionTextType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Consignment" minOccurs="0" maxOccurs="9999">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="AdditionalDocument" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<!--법령일련번호-->
										<xsd:element name="CriteriaConformanceID" type="kcsds:AdditionalDocumentCriteriaConformanceIdentificationIDType" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Amendment">
								<xsd:complexType>
									<xsd:sequence>
										<!--구분(01:란추가, 02:란삭제, 03:란정정)-->
										<xsd:element name="ChangeReasonCode" type="ds:AmendmentChangeReasonCodeType" minOccurs="0"/>
										<!--정정전-->
										<xsd:element name="StatementDescription" type="ds:AmendmentStatementDescriptionTextType" minOccurs="0"/>
										<!--정정후-->
										<xsd:element name="AdjustmentDescription" type="kcsds:AmendmentAdjustmentDescriptionTextType" minOccurs="0"/>
										<xsd:element name="Pointer">
											<xsd:complexType>
												<xsd:sequence>
													<!--정정항목 란번호-->
													<xsd:element name="SequenceNumeric" type="ds:PointerSequenceNumericType"/>
													<!--규격번호-->
													<xsd:element name="DocumentSectionCode" type="ds:PointerDocumentSectionCodeType"/>
													<!--항목번호-->
													<xsd:element name="TagID" type="ds:PointerTagIDType"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="ConsignmentItem" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Commodity" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<!--차대관리번호-->
													<xsd:element name="ID" type="ds:CommodityIdentificationIDType" minOccurs="0"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="TransportEquipment" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<!--컨테이너 일련번호-->
										<xsd:element name="ID" type="ds:TransportEquipmentIdentificationIDType" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Exporter">
					<xsd:complexType>
						<xsd:sequence>
							<!--수출화주 통관고유부호-->
							<xsd:element name="ID" type="ds:ExporterIdentificationIDType" minOccurs="0"/>
							<!--수출화주 상호 또는 성명-->
							<xsd:element name="Name" type="ds:ExporterNameTextType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Submitter" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<!--신고인 부호-->
							<xsd:element name="ID" type="ds:SubmitterIdentificationIDType" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== kosoup/Customs-Automation/references/수출정정신고/KCS_DeclarationOfEXP_5ASSchemaModule_1.0_standard.xml
<?xml version="1.0" encoding="UTF-8"?>
<wco:Declaration xmlns:kcs="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_5ASSchemaModule:1:0" xmlns:wco="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_5ASSchemaModule:1:0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_5ASSchemaModule:1:0 ../../schema4G/kcs/data/standard/KCS_DeclarationOfEXP_5ASSchemaModule_1.0_standard.xsd">
	<!--확정일자-->
	<wco:AcceptanceDateTime>20201209</wco:AcceptanceDateTime>
	<!--신고세관/과-->
	<wco:DeclarationOfficeID>01020</wco:DeclarationOfficeID>
	<!--수출신고번호-->
	<wco:ID>000000000000000</wco:ID>
	<!--신청일자(CCYYMMDD)-->
	<wco:IssueDateTime>20140506</wco:IssueDateTime>
	<!--문서형태구분-->
	<wco:TypeCode>GOVCBR5AS</wco:TypeCode>
	<!--신청차수-->
	<wco:VersionID>3</wco:VersionID>
	<!--구분-->
	<wco:TransactionNatureCode>A</wco:TransactionNatureCode>
	<!--귀책사유-->
	<kcs:Reason>귀책사유</kcs:Reason>
	<wco:AdditionalInformation>
		<!--정정코드-->
		<wco:StatementCode>01</wco:StatementCode>
		<!--정정/연장사유-->
		<wco:StatementDescription>정정/연장사유</wco:StatementDescription>
	</wco:AdditionalInformation>
	<!--0..9999 반복-->
	<wco:Consignment>
		<wco:AdditionalDocument>
			<!--법령일련번호-->
			<kcs:CriteriaConformanceID>01</kcs:CriteriaConformanceID>
		</wco:AdditionalDocument>
		<wco:Amendment>
			<!--구분(01:란추가, 02:란삭제, 03:란정정)-->
			<wco:ChangeReasonCode>01</wco:ChangeReasonCode>
			<!--정정전-->
			<wco:StatementDescription>정정전</wco:StatementDescription>
			<!--정정후-->
			<kcs:AdjustmentDescription>정정후</kcs:AdjustmentDescription>
			<wco:Pointer>
				<!--정정항목 란번호-->
				<wco:SequenceNumeric>001</wco:SequenceNumeric>
				<!--규격번호-->
				<wco:DocumentSectionCode>000000</wco:DocumentSectionCode>
				<!--항목번호-->
				<wco:TagID>123</wco:TagID>
			</wco:Pointer>
		</wco:Amendment>
		<wco:ConsignmentItem>
			<wco:Commodity>
				<!--차대관리번호-->
				<wco:ID>001</wco:ID>
			</wco:Commodity>
		</wco:ConsignmentItem>
		<wco:TransportEquipment>
			<!--컨테이너 일련번호-->
			<wco:ID>1</wco:ID>
		</wco:TransportEquipment>
	</wco:Consignment>
	<wco:Exporter>
		<!--수출화주 통관고유부호-->
		<wco:ID>00000000000000</wco:ID>
		<!--수출화주 상호 또는 성명-->
		<wco:Name>김수출</wco:Name>
	</wco:Exporter>
	<wco:Submitter>
		<!--신고인 부호-->
		<wco:ID>00001</wco:ID>
	</wco:Submitter>
</wco:Declaration>
