=== kosoup/Customs-Automation/references/전자상거래 수출관련 서식/GOVCBRDJR/KCS_DeclarationOfEXP_DJRSchemaModule_1.0_standard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Module: KCS_DeclarationOfEXP_DJR
Name: 전자상거래 수출 이행완료 신고서
Agency: Korea Customs Service
KCSBusinessType : EXP
AgencyAssignedCustomizedDocumentName : GOVCBR_DJR
Version: 1.0 Rev. 0
Last change: 2019.11.08
Author : yh.kim

Change :
 
 Copyright (C) Korea Customs Service (2014). All Rights Reserved. 
-->
<xsd:schema xmlns="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJRSchemaModule:1:0" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:ds="urn:wco:datamodel:WCO:DS:1" xmlns:kcsds="urn:kr:gov:kcs:data:standard:KCSDS:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJRSchemaModule:1:0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:import namespace="urn:wco:datamodel:WCO:DS:1" schemaLocation="../../../wco/common/DS_1p0.xsd"/>
	<xsd:import namespace="urn:kr:gov:kcs:data:standard:KCSDS:1" schemaLocation="../../common/KCSDS_1p0.xsd"/>
	<xsd:element name="Declaration">
		<xsd:complexType>
			<xsd:sequence>
				<!--전송구분-->
				<xsd:element name="FunctionCode" type="ds:DeclarationFunctionCodeType"/>
				<!--신고번호-->
				<xsd:element name="ID" type="ds:DeclarationIdentificationIDType"/>
				<!--문서형태구분-->
				<xsd:element name="TypeCode" type="ds:DeclarationTypeCodeType"/>
				<!--신고구분-->
				<xsd:element name="TransactionNatureCode" type="ds:DeclarationTransactionNatureCodeType"/>
				<xsd:element name="AdditionalDocument" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<!--주문번호-->
							<xsd:element name="ID" type="ds:AdditionalDocumentIdentificationIDType" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="BorderTransportMeans">
					<xsd:complexType>
						<xsd:sequence>
							<!--출항일시-->
							<xsd:element name="DepartureDateTime" type="ds:BorderTransportMeansDepartureDateTimeType"/>
							<!--선박항공편명-->
							<xsd:element name="ScheduledConveyanceID" type="ds:BorderTransportMeansScheduledConveyanceIDType"/>
							<!--해상/항공 구분-->
							<xsd:element name="TypeCode" type="ds:BorderTransportMeansTypeCodeType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Exporter">
					<xsd:complexType>
						<xsd:sequence>
							<!--수출화주 신고인 부호-->
							<xsd:element name="ID" type="ds:ExporterIdentificationIDType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="GoodsShipment">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="AdditionalDocument">
								<xsd:complexType>
									<xsd:sequence>
										<!--배송신고번호-->
										<xsd:element name="ID" type="ds:AdditionalDocumentIdentificationIDType"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Destination">
								<xsd:complexType>
									<xsd:sequence>
										<!--목적국-->
										<xsd:element name="CountryCode" type="ds:DestinationCountryCodeType"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="GovernmentAgencyGoodsItem">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Commodity">
											<xsd:complexType>
												<xsd:sequence>
													<!--이행수량-->
													<xsd:element name="CountQuantity" type="ds:CommodityCountQuantityType"/>
													<!--이행중량-->
													<xsd:element name="SizeMeasure" type="ds:CommoditySizeMeasureType"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="PreviousDocument" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<!--전자상거래수출신고번호-->
							<xsd:element name="ID" type="ds:PreviousDocumentIdentificationIDType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== kosoup/Customs-Automation/references/전자상거래 수출관련 서식/GOVCBRDJR/KCS_DeclarationOfEXP_DJRSchemaModule_1.0_standard.xml
<?xml version="1.0" encoding="UTF-8"?>
<wco:Declaration
    xmlns:kcs="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJRSchemaModule:1:0"
    xmlns:wco="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJRSchemaModule:1:0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:kr:gov:kcs:data:standard:KCS_DeclarationOfEXP_DJRSchemaModule:1:0 ../../schema4G/kcs/data/standard/KCS_DeclarationOfEXP_DJRSchemaModule_1.0_standard.xsd">
    <!--전송구분-->
    <wco:FunctionCode>01</wco:FunctionCode>
    <!--신고번호-->
    <wco:ID>99999999</wco:ID>
    <!--문서형태구분-->
    <wco:TypeCode>GOVCBRDJP</wco:TypeCode>
    <!--신고구분-->
    <wco:TransactionNatureCode>01</wco:TransactionNatureCode>
    
    <wco:AdditionalDocument>
        <!--주문번호-->
        <wco:ID>A123456</wco:ID>
    </wco:AdditionalDocument>
    
     <wco:BorderTransportMeans>
        <!--출항일시-->
        <wco:DepartureDateTime>20191108123030</wco:DepartureDateTime>
        <!--선박항공편명-->
        <wco:ScheduledConveyanceID>A123456</wco:ScheduledConveyanceID>
        <!--해상/항공 구분-->
        <wco:TypeCode>01</wco:TypeCode>
    </wco:BorderTransportMeans>
    
    <wco:Exporter>
        <!--수출화주 신고인 부호-->
        <wco:ID>99999999</wco:ID>
    </wco:Exporter>
	
	<wco:GoodsShipment>
        <wco:AdditionalDocument>
            <!--배송신고번호-->
            <wco:ID>9999999999</wco:ID>
        </wco:AdditionalDocument>
         <wco:Destination>
            <!--목적국-->
            <wco:CountryCode>KOR</wco:CountryCode>
        </wco:Destination>
        <wco:GovernmentAgencyGoodsItem>
            <wco:Commodity>
                <!--이행수량-->
                <wco:CountQuantity>999999999</wco:CountQuantity>
                <!--이행중량-->
                <wco:SizeMeasure>999999</wco:SizeMeasure>
            </wco:Commodity>
        </wco:GovernmentAgencyGoodsItem>
    </wco:GoodsShipment>
    
    <wco:PreviousDocument>
        <!--전자상거래수출신고번호-->
        <wco:ID>A123456</wco:ID>
    </wco:PreviousDocument>
</wco:Declaration>
